{
 "title": "Grafana Cloud Billing/Usage",
 "description": "Grafana Cloud Billing/Usage Dashboard",
 "tags": [ "billing" ],
 "time": { "from": "now/M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "included_metrics",
    "label": "Included Metrics Series",
    "query": "label_values(grafanacloud_org_info, metrics_included_series)"
   },
   {
    "name": "included_logs",
    "label": "Included Logs",
    "query": "label_values(grafanacloud_org_info, logs_included_usage)"
   }
  ]
 },
 "panels": [
  { "title": "Billable Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current Total Additional Usage Amount",
   "type": "stat",
   "gridPos": { "h": 4, "w": 15, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "prefix:$" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "grafanacloud_org_metrics_overage + grafanacloud_org_logs_overage",
     "legendFormat": "Metrics"
    }
   ]
  },
  {
   "title": "How Billing Works",
   "type": "text",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 1 },
   "options": {
    "content": "Metrics and logs are billed based on ingestion. For Metrics, we bill based on the number of active series using the 95th percentile during the period. [Learn more here](\nhttps://grafana.com/docs/grafana-cloud/billing-and-usage/)."
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Current Billable Metrics Series",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "grafanacloud_org_metrics_billable_series"
    }
   ]
  },
  {
   "title": "Current Metrics Additional Usage Amount",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "prefix:$" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "grafanacloud_org_metrics_overage"
    }
   ]
  },
  {
   "title": "Current Billable Logs Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "grafanacloud_org_logs_usage" }
   ]
  },
  {
   "title": "Current Logs Additional Usage Amount",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "prefix:$" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "grafanacloud_org_logs_overage" }
   ]
  },
  {
   "title": "Total Billable Metrics Series",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grafanacloud_org_metrics_billable_series",
     "legendFormat": "Billable Series"
    },
    {
     "expr": "grafanacloud_org_metrics_overage",
     "legendFormat": "Additional Usage Amount"
    },
    {
     "expr": "grafanacloud_org_info * $included_metrics",
     "legendFormat": "Included Series"
    }
   ]
  },
  {
   "title": "Total Billable Logs Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    { "expr": "grafanacloud_org_logs_usage", "legendFormat": "Billable Usage" },
    { "expr": "grafanacloud_org_logs_overage", "legendFormat": "Additional Usage Amount" },
    {
     "expr": "grafanacloud_org_info * $included_logs",
     "legendFormat": "Included Usage"
    }
   ]
  },
  { "title": "Metrics Instance Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Active Series",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(grafanacloud_instance_active_series) by (id) * on (id) group_left(name) grafanacloud_instance_info",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Ingestion Rate (DPM)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(grafanacloud_instance_samples_per_second * 60) by (id) * on(id) group_left(name) grafanacloud_instance_info",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Discarded Samples",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(max(grafanacloud_instance_samples_discarded_per_second) by (id, reason)) by (id, reason) * on(id) group_left(name) grafanacloud_instance_info",
     "legendFormat": "{{name}} — {{reason}}"
    }
   ]
  },
  { "title": "Logs Instance Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Ingestion Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(grafanacloud_logs_instance_bytes_received_per_second) by (id) * on(id) group_left(name) grafanacloud_logs_instance_info",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Ingested Data by Day",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(sum_over_time((grafanacloud_logs_instance_bytes_received_per_second * 60)[1d:1m])) by (id) * on(id) group_left(name) grafanacloud_logs_instance_info ",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Discarded Samples",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(grafanacloud_logs_instance_samples_discarded_per_second * 60) by (id, reason) * on(id) group_left(name) grafanacloud_logs_instance_info",
     "legendFormat": "{{name}} — {{reason}}"
    }
   ]
  }
 ]
}